### ISSUE TITLE
Incorrect behavior for RenderImage with mw attribute

### ISSUE THREAD

**Issue by BenGGolden** [mikeedwards83/Glass.Mapper#133] opened 2015-05-08 19:18 UTC
I have code like this in my views
```
@RendeImage(m => m.Image, new { mw = 200 })
```
This is being rendered as
```
<img src='~/media/Images/myImage.ashx?h=250&amp;w=300&amp;mw=156&hash=[omitted]' />
```
This causes the image to have black bars on top and bottom.  I have seen this issue in later releases of v3 as well as v4.  `@Editable` also seems to have this issue.  `@Html.Sitecore().Field()` does not have this problem.  Is there a way to avoid Glass's custom image rendering logic and just run the normal renderField pipeline?

Thanks,
-Ben

**Comment by mikeedwards83** [comment] 2015-05-19 09:38
I Ben, I am working on changing the image rendering logic. Please take a look at branch feature/issue133 https://github.com/mikeedwards83/Glass.Mapper/commit/b078d9278abdbff85368db8f3e983d79b91ce32b

**Comment by mikeedwards83** [comment] 2015-05-19 12:22
I have pushed a fix to our develop branch. This is available from the nightly build as 4.0.1.27

**Comment by BenGGolden** [comment] 2015-05-19 13:54
Thanks, Mike.  I'll try to take a look later this week.

**Comment by mikeedwards83** [comment] 2015-06-18 09:10
This has been release in 4.0.1.8, reopen if this is still and issue.

**Closed by mikeedwards83** 2015-06-18 09:10 UTC
Labels: 1 - Ready, bug

**Comment by colema18** [comment] 2015-12-16 16:10
On 4.0.1.8 and I am now seeing output that doesn't seem to add up.

@RenderImage(article, x => x.Image, new {MW = 180, MH = 180}, true)

is being rendered as:

<img src="/~/media/images/imageName.ashx?mh=180&amp;la=en&amp;h=45&amp;w=111&amp;mw=180" alt="altText">

The raw image is 500 x 365 so I would think the html should have the h=131 and the w=180.

~james

**Comment by loueradun** [comment] 2020-07-02 18:07
I believe this issue should be re-opened.  I am currently experiencing exactly the same issue on latest 5.6.160.

I have tried the following:
@Html.Glass().RenderImage(Model, x => x.Image, new { mw = 1000, mh = 1000 }, isEditable: true, outputHeightWidth: false)
@Html.Glass().RenderImage(Model, x => x.Image, new { height = 0, width = 0, mw = 1000, mh = 1000 }, isEditable: true, outputHeightWidth: false)
@Html.Glass().RenderImage(Model, x => x.Image, new { h = 0, w = 0, mw = 1000, mh = 1000 }, isEditable: true, outputHeightWidth: false)
@Html.Glass().RenderImage(Model, x => x.Image, new { h = (string)null, w = (string)null, mw = 1000, mh = 1000 }, isEditable: true, outputHeightWidth: false)
@Html.Glass().RenderImage(Model, x => x.Image, new { mw = 1000, mh = 1000 }, isEditable: true)
@Html.Glass().RenderImage(Model, x => x.Image, new { height = 0, width = 0, mw = 1000, mh = 1000 }, isEditable: true)
@Html.Glass().RenderImage(Model, x => x.Image, new { h = 0, w = 0, mw = 1000, mh = 1000 }, isEditable: true)
@Html.Glass().RenderImage(Model, x => x.Image, new { h = (string)null, w = (string)null, mw = 1000, mh = 1000 }, isEditable: true)

All output a url that looks like this:
https://site/imageName.ashx?mh=1000&la=en&h=916&w=1000&mw=1000&hash=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

If I remove the properties object I get this (the values below are the native image w/h, but not set in page content):
https://site/imageName.ashx?h=1238&w=1352&la=en&hash=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

no matter what I do I can not get it to not output the width and height.  Either this bug has been re-introduced or I must be doing something wrong.  This is causing a lot of grief with my Image processing plugin (dianoga).

**Comment by loueradun** [comment] 2020-07-02 18:26
I just want to add that I can also reproduce in 5.7.162-alpha release as well.
