### ISSUE TITLE
RenderField pipeline only called in editing mode

### ISSUE THREAD

**Issue by aquasonic** [mikeedwards83/Glass.Mapper#98] opened 2014-12-31 13:21 UTC
Hi Mike,

I have a Rich Text field on my page, where I add some additional markup for links in the `renderField` pipeline (e.g. adding always `target_"blank"` to some links). In my Razor view I added the field with an `@Editable()`:

    @Editable(m => m.Text)

This works as expected in editing mode, but not when I'm not in editing mode. In the `GlassHtml` class I saw, that the `renderField` pipeline in only called in editing mode (see [here](https://github.com/mikeedwards83/Glass.Mapper/blob/667f1980e7ba0372592b8594f6fc059704d48fc5/Source/Glass.Mapper.Sc/GlassHtml.cs#L609)). Why don't you call the pipeline when not in editing mode? Is there a solution/workaround I can still use the pipeline when I'm not in editing mode?

Thanks for looking into it and regards,
Kevin

**Comment by mikeedwards83** [comment] 2015-01-01 18:13
Kevin 

The renderField pipeline is only called during edit mode for all field types except Rich Text. If a field is a rich text field it is actually called by the SitecoreFieldStringMapper:

https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source/Glass.Mapper.Sc/DataMappers/SitecoreFieldStringMapper.cs#L69

To test is this is working or if there is a problem see if the links and images in a Rich Text field are being correctly replaced. If they are then the renderField pipeline is being called correctly.

The reason that for all other field types I don't call the pipeline is for speed and also because it is no necessary. If you have mapped a date to a DateTime object then you don't need to push that object through the renderField pipeline to output data.

Mike

**Comment by aquasonic** [comment] 2015-01-06 07:45
Hi Mike,

thanks for your reply. It was my fault. In the domain model I found this setting:

    [SitecoreField(FieldName = "Text", Setting = SitecoreFieldSettings.RichTextRaw)]

And with this, it seems that the renderField pipeline is only called in editing mode (which make sense to me). I'm sorry about the mistake.

Thanks anyway and regards,
Kevin

**Comment by RollForReflex** [comment] 2015-06-08 23:24
Hi Mike,

I have a similar question regarding the RenderField pipeline not being called for Single-Line Text fields. I'm leveraging Glass Mapper to do some custom token replacement on a Single-Line Text field but currently the replacement is only displayed in editing mode and I'd like this to be something shown to the end user.

Currently it seems my options are to use Html.Sitecore.Field(), turn the field type into Rich Text (which is fine, but not really needed), or to do a lengthy workaround like the one mentioned here:
http://www.robertgray.net.au/posts/utilising-the-render-field-pipeline-when-using-glass-for-sitecore#.VXYi689VhBc

I'm wondering if there's potential for an override to be made on the Editable call that allows a developer to explicitly invoke the RenderField pipeline if they want to, knowing full well about the overhead associated with it. If you think this may be a worthy endeavor, I'd be glad to work on a PR for you, but if not I'm curious as to what you think the best solution is currently.

Thanks so much for your great work on Glass!

-W

**Comment by patrickperrone** [comment] 2015-09-25 18:50
I'm in the same boat as RollForReflex. +1 for an override to Editable feature.

**Comment by mikeedwards83** [comment] 2015-09-29 09:22
This issue has been fixed in release 4.0.3.50

**Closed by mikeedwards83** 2015-09-29 09:22 UTC

**Comment by patrickperrone** [comment] 2015-09-29 18:04
Thanks, Mike!

**Comment by klinden** [comment] 2016-05-02 16:39
Just curious, what exactly was fixed? I'm using RenderLink to render some general link fields, but it appears that the RenderField pipeline is not being run.

**Comment by mikeedwards83** [comment] 2016-05-04 11:04
I think we added the field setting SitecoreFieldSettings.ForceRenderField which forces a string field to use the renderfield pipeline.

**Comment by bewards** [comment] 2018-10-16 20:17
Is this a setting that can be applied globally for SLT fields?

**Comment by cardinal252** [comment] 2018-10-16 20:56
The better option is to actually override the string mapper or glass html in the majority of cases :D

**Comment by bewards** [comment] 2018-10-16 21:20
Trying to understand how to override/replace the string mapper. The string field mapper class is new'd up and injected into a DataMapper factory. How can I gain access to overriding this class? 

The Nuget package gives me  `GlassMapperScCustom.cs` where I can add maps and do PostLoad logic. The PostLoad method in this class lets me play with an instance of IDependencyResolver so I think that is where i would get the datamapper factory and somehow *replace* `SitecoreFieldStringMapper`?

**Comment by bewards** [comment] 2018-10-17 14:53
I read that post and understand how to add a custom mapper, but would it not make more sense to replace `SitecoreFieldStringMapper` since I want **all** SLT and MLT fields to be processed by `renderField`? By adding a new one that extends it, wouldn't both mappers run? Or is replacing not a good option?

**Comment by cardinal252** [comment] 2018-10-17 15:07
Ok, so ... What is the goal in manipulating the RenderField pipeline?

If it is to add markup (say for example) token processing to the output (which sounds like what you are doing) then you can simply either override GlassHtml or the field mapper to do the same thing whilst not losing the performance gain that avoiding the renderfield pipeline affords. Glass by design skips this pipeline to be faster, and in certain scenarios can actually render Sitecore content faster than Sitecore can. The choice between overriding GlassHtml and the field mapper largely depends on whether you would want the same replacements to be made in non-presentation scenarios - modifying GlassHtml would usually only modify output at a view level for like @Html.Glass().Editable()

The only time this generally causes a problem is if you are mixing glass and non-glass presentation (into which you may require explicitly calling the render field pipeline). Otherwise, you are simply modifying the wrong code to achieve what you need.

Hope this helps :D

**Comment by linasw** [comment] 2023-05-10 11:02
@bewards I know it's and old topic, but did you manage to modify GlassHtml? I am trying to achieve the same, by having some global tokens which I want to be replaced when using @Html.Glass.Editable().
