### ISSUE TITLE
Extending Html Helpers with namevalue collection

### ISSUE THREAD

**Issue by STDGA** [mikeedwards83/Glass.Mapper#367] opened 2019-02-02 12:23 UTC
Hi,
currently it is a bit hard to extend glass helpers with custom html helpers, as an example the Render image accept only anonymous object and it uses the "Utilities" class to convert it to Namevaluecollection.
It makes it really easier for us if we can pass in NameValueCollection from our helper directly to the Glass Html helpers.

I have already created Pull request [here](https://github.com/mikeedwards83/Glass.Mapper/pull/366): 
https://github.com/mikeedwards83/Glass.Mapper/pull/366

Thank you

**Comment by mikeedwards83** [comment] 2019-05-17 07:05
I have merged the change into the release. I will close this issue because it is a duplicate of #366

**Closed by mikeedwards83** 2019-05-17 07:05 UTC
Labels: duplicate
