### ISSUE TITLE
Wrong behavior with duplicated names on same template

### ISSUE THREAD

**Issue by gomnet** [mikeedwards83/Glass.Mapper#312] opened 2017-06-14 08:55 UTC
After dealing with this problem, it seems Sitecore API is getting the data properly of every field (even with duplicated names):

Sitecore.Context.Database.GetItem("{my-item-guid}").Fields[new Sitecore.Data.ID("{my-field-guid}")]

But when Glass is getting the fields by ID, the content for 2 fields with same name (on different sections) is always the same:

[SitecoreField(FieldsIDs.ReviewBody)]
public virtual string ReviewBody { get; set; } 
[SitecoreField(FieldsIDs.InterstitialBody)]
public virtual string InterstitialBody { get; set; } 
![glass-issue](https://user-images.githubusercontent.com/25245116/27123916-93ac2508-50ef-11e7-8fb8-8d6b782b797b.png)

So, please could you solve this? By the moment, we gonna change the name for avoiding duplicated names.

Thanks a lot in advance.

Best regards,
David.

**Comment by shindai** [comment] 2017-06-20 11:48
Take a look at my issue created the same time as you, [here](https://github.com/mikeedwards83/Glass.Mapper/issues/311).
The GlassMapper-Developer alone can't solve this, the fix requires an API-Change in Sitecore.Kernel.
But I did not create an support ticket for that in the sitecore helpdesk, because the change requires also changes in the glassmapper code then.

**Comment by mikeedwards83** [comment] 2017-06-29 16:59
Closing because it is a duplicate of #311

**Closed** 2017-06-29 17:04 UTC
