### ISSUE TITLE
GlassMapper 4 Sitecore 8.1

### ISSUE THREAD

**Issue by Sitecoreclimber** [mikeedwards83/Glass.Mapper#183] opened 2015-10-24 07:26 UTC
Hey,
I'm trying to install GlassMapper on a Sitecore 8.1 solution and I'm receiving next errors: 

PM> Install-Package Glass.Mapper.Sc
Attempting to resolve dependency 'Castle.Core (= 3.3.3)'.
'Glass.Mapper.Sc 4.0.3.51' already installed.
Adding 'Castle.Core 3.3.3' to SitecoreDemo.Website.
Successfully added 'Castle.Core 3.3.3' to SitecoreDemo.Website.
Adding 'Glass.Mapper.Sc 4.0.3.51' to SitecoreDemo.Website.
Successfully added 'Glass.Mapper.Sc 4.0.3.51' to SitecoreDemo.Website.
Check Version of  Sitecore.Kernel
Sitecore.Kernel Path: D:\Dev\CompanyName\TemplateSitecore\Lib\Sitecore.Kernel.dll
Check Sitecore.Kernel File Version is 8.1.0.5297
Adding reference to  D:\Dev\CompanyName\TemplateSitecore\SitecoreDemo.Solution\packages\Glass.Mapper.Sc.4.0.3.51\lib\81\Glass.Mapper.Sc.dll
Exception calling "Add" with "1" argument(s): "Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))"
At D:\Dev\CompanyName\TemplateSitecore\SitecoreDemo.Solution\packages\Glass.Mapper.Sc.4.0.3.51\tools\install.ps1:45 char:3
+         $project.Object.References.Add($path);
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ComMethodTargetInvocation
 
The property 'CopyLocal' cannot be found on this object. Verify that the property exists and can be set.
At D:\Dev\CompanyName\TemplateSitecore\SitecoreDemo.Solution\packages\Glass.Mapper.Sc.4.0.3.51\tools\install.ps1:46 char:3
+         $project.Object.References.Item($name).CopyLocal = "True"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
Check Version of  System.Web.Mvc
System.Web.Mvc Path: D:\Dev\CompanyName\TemplateSitecore\Lib\System.Web.Mvc.dll
Check System.Web.Mvc File Version is 5.2.30128.0
Adding reference to  D:\Dev\CompanyName\TemplateSitecore\SitecoreDemo.Solution\packages\Glass.Mapper.Sc.4.0.3.51\lib\Mvc5\Glass.Mapper.Sc.Mvc.dll
Installation complete

**Comment by joosthollander** [comment] 2015-10-24 11:46
Hi,

I ran into the same problem. It seems that 8.1 is not supported yet. The install script is looking for a 8.1 folder which does not exist. If you temporally reference an 8.0 update x Sitecore.Kernel before you install Glass it will install but of-course this is a hack. I am currently finding out if there are other compatibility issues. 
@mikeedwards83 Any news on 8.1? Do I need to make a 8.1 specific built of Glass?

Regards,
Joost

**Comment by mikeedwards83** [comment] 2015-10-26 08:16
We have pushed 8.1 support to the nightly build. You can download it from the Glass nightly build server. We will make an official release later this week.

**Comment by pault70** [comment] 2015-11-02 14:35
Downloaded the latest nightly 4.03.60-beta and get the same error when trying to add to an 8.1 sitecore install.

**Comment by mikeedwards83** [comment] 2015-11-02 17:26
@pault70  I have just tested with the same version and it worked for me. I am using SC assemblies 8.1.0.5297.

**Comment by pault70** [comment] 2015-11-03 08:31
Not sure where I get those sitecore assemblies from, I have the latest official release and it's v 8.1.0.0

**Comment by mikeedwards83** [comment] 2015-11-07 18:12
Released in 4.0.4

**Closed by mikeedwards83** 2015-11-07 18:12 UTC
Labels: 1 - Ready, enhancement

**Comment by argha007** [comment] 2017-03-27 19:03
How to get latest "Glass.Mapper.Sc.Mvc" dll or nuget package for Glass.Mapper.Sc 4.3.4.197 (this version ??? Please help

**Comment by mikeedwards83** [comment] 2017-03-30 17:17
When you install Glass.Mapper.Sc.Core the package uses a powershell script to determine which version of System.Web.Mvc your project references. It will then pick the correct version of the Glass.Mapper.Sc.Mvc.dll to add to your project.

Normally if the Glass.Mapper.Sc.Mvc.dll is not being referenced after the install then it is normally because the project itself does not reference System.Web.Mvc.

To solve add the System.Web.Mvc and then reinstall the Glass.Mapper.Sc.Core nuget package.

**Comment by argha007** [comment] 2017-04-06 20:06
Hi Mike,
We are getting below issue for some of the components after upgrading glass mapper... Any insight Please? Thanks & Appreciate your Co-Operation in Advance!!!

`GlassMapper error  "Configuration Resolver pipeline did not return a type. Has the type been loaded by Glass.Mapper. Type: System.Object"`

image attached
<img width="960" alt="argha" src="https://cloud.githubusercontent.com/assets/22396796/24773375/4128f154-1b15-11e7-827d-dbaa140edc25.png">

**Comment by mikeedwards83** [comment] 2017-04-13 14:45
Hi

This is normally caused by a property of type System.Object on the model. You need to find the property and either change the return type of mark it with SitecoreIgnore.

**Comment by argha007** [comment] 2017-04-13 18:51
What data type to change then from object? Will sitecore ignore work hw it
was working in previous vetsions? I meant the existing functionality will
not be hampered correct?
