### ISSUE TITLE
RegexViewTypeResolver: View Type not resolved when namespace removed from Model type

### ISSUE THREAD

**Issue by deeja** [mikeedwards83/Glass.Mapper#275] opened 2017-01-04 16:44 UTC
`GetModelFromView` is not picking up the model where the type has the namespace removed.
RegexViewTypeResolver seems to be the culprit.
Doesn't resolve:
```
@using Something.Doodalies.Extensions;
@using Something.Models.sitecore.templates.Doodalies.Page_Types;
@inherits Glass.Mapper.Sc.Web.Mvc.GlassView<I_BasePage>
```

Does Resolve
```
@using Something.Doodalies.Extensions;
@using Something.Models.sitecore.templates.Doodalies.Page_Types;
@inherits Glass.Mapper.Sc.Web.Mvc.GlassView<Something.Models.sitecore.templates.Doodalies.Page_Types.I_BasePage>
```

**Comment by mikeedwards83** [comment] 2017-01-04 16:52
This is odd because we added to the regex the ability to check using statements:

https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source/Glass.Mapper.Sc.Mvc/Pipelines/Response/RegexViewTypeResolver.cs#L75

Is there an issue with this regex?

https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source/Glass.Mapper.Sc.Mvc/Pipelines/Response/RegexViewTypeResolver.cs#L20

**Comment by deeja** [comment] 2017-01-04 17:05
Doesn't appear to be an issue with the matching, at least when testing it in notepad++

**Comment by cardinal252** [comment] 2017-01-17 15:05
Could we get a copy of the actual razor file for analysis (you can change the namespace to protect the client if necessary) - please email it to myself or mike ?

**Comment by mikeedwards83** [comment] 2017-02-19 21:13
Hi Deeja 

Can you send me the actual file at Hello@glass.lu? If not we will have to close this issue.

**Comment by deeja** [comment] 2017-02-20 10:22
Here are three files that seem to have the issue. 
[regexmodelfinder.zip](https://github.com/mikeedwards83/Glass.Mapper/files/787149/regexmodelfinder.zip)

```
~/views/NavigationFeature/SidebarNavigation.cshtml: Failed to process view '~/views/NavigationFeature/SidebarNavigation.cshtml'
Inner Exception The model item passed into the dictionary is of type 'Sitecore.Mvc.Presentation.RenderingModel', but this dictionary requires a model item of type 'PandaExpress.Models.sitecore.templates.Feature.Navigation.ISidebarNavigationHeading'.
   at System.Web.Mvc.ViewDataDictionary`1.SetModel(Object value)
   at System.Web.Mvc.ViewDataDictionary..ctor(ViewDataDictionary dictionary)
   at System.Web.Mvc.WebViewPage`1.SetViewData(ViewDataDictionary viewData)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer)
~/views/NavigationFeature/SidebarNavigation.cshtml: Failed to process view '~/views/NavigationFeature/SidebarNavigation.cshtml'
```

**Comment by cardinal252** [comment] 2017-02-20 11:02
Hi Deeja,

I just ran this view file through the RegexTypeResolver and the issue appears to be caused by the trailing semicolon on the using statements in the view. Please remove them and let us know if this is your issue?

@mikeedwards83 I have added a potential fix on the branch feature/issue-275 for your review.

**Comment by deeja** [comment] 2017-02-20 12:27
@cardinal252  Removing the semicolon seems to work for the first two files, but not the footer.cshtml. 
 I could try to modify to find out why this is the case, if you are not able to replicate.

**Comment by cardinal252** [comment] 2017-02-20 12:38
With the semi-colons removed, the regular expressions used to parse the view file are matching correctly. The error you are seeing can also manifest if the item that is used comes back as a null from Glass Mapper.

The older version of the regex is this @using\s+(?<namespace>[^\n\s]+), I tested it using https://regex101.com/ and by writing a unit test that uses your supplied file, both seem to work

**Comment by mikeedwards83** [comment] 2017-02-21 18:57
@cardinal252  I have merged your change.

**Comment by mikeedwards83** [comment] 2017-09-21 14:05
In release 4.4.0

**Closed by mikeedwards83** 2017-09-21 14:05 UTC
